### ISSUE TITLE
[Bug] Plugin won't start on 1.20.4

### ISSUE THREAD

**Issue by IkyMax** [math0898/OfflinePlayers#2]
**Describe the bug**
The plugin isn't working on 1.20.4

**To Reproduce**
1. Simply start the server and wait

**Information to investigate**
- Server Version
1.20.4
- Console logs
[09:53:08 ERROR]: [OfflinePlayers] Error initializing plugin 'OfflinePlayers-refresh-optimize-3.3.1.jar' in folder 'plugins' (Is it up to date?)
java.lang.NoClassDefFoundError: com/palmergames/bukkit/towny/exceptions/TownyException
        at de.snap20lp.offlineplayers.OfflinePlayers.onLoad(OfflinePlayers.java:57) ~[OfflinePlayers-refresh-optimize-3.3.1.jar:?]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[paper-1.20.4.jar:git-Paper-485]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[paper-1.20.4.jar:git-Paper-485]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[paper-1.20.4.jar:git-Paper-485]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.20.4.jar:git-Paper-485]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.loadPlugins(CraftServer.java:507) ~[paper-1.20.4.jar:git-Paper-485]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:274) ~[paper-1.20.4.jar:git-Paper-485]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1131) ~[paper-1.20.4.jar:git-Paper-485]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-485]
        at java.lang.Thread.run(Thread.java:1623) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.palmergames.bukkit.towny.exceptions.TownyException
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        ... 10 more
- Spigot or Bukkit
Paper-spigot

**Comment by math0898** [comment]
This is due to Towny being used in the MortalMaker system. I attempt to get the TownyAPI in an unsafe manor. Should be an easy fix.

**Comment by math0898** [comment]
The merge request missed some code segments. I'll fix the oversight and push directly to master. At that time I'll mark this issue as resolved.
